### PR TITLE
[memgraph-2-17 < ] Debugging memgraph

### PR DESCRIPTION
**Pull request by Josipmrden**
### Description

Instructions on how to debug Memgraph when in `RelWithDebInfo` mode with the tools inside the container.

### Pull request type

Please check what kind of PR this is:

- [ ] Fix or improvement of an existing page
- [X] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
@MarkoBarisic tag the PR when you add linux-perf, gdb and procps to the RelWithDebInfo image

### Checklist:

- [x] Check all content with Grammarly
- [x] Perform a self-review of my code
- [x] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [x] The build passes locally
- [x] My changes generate no new warnings or errors
- [x] Add a corresponding label
- [x] If release-related, add a product and version label (update to docs when we start releasing relwithdebinfo images)
- [x] If release-related, add release note on product PR (update to docs when we start releasing relwithdebinfo images)

### CODE REVIEW

**Comment by Josipmrden** [comment]
@kgolubic can you check why my image at the bottom does not show in the dev environment?

**Comment by Josipmrden** [comment]
@kgolubic need 2 more links and then we'll be fine

**Comment by kgolubic** [comment]
> @kgolubic can you check why my image at the bottom does not show in the dev environment?

The images need to go to `/public/pages/` folder, not directly in the folder where the page is located. I've moved the image to the right location.

@Josipmrden, once you are done, I'll take over this this PR. There are some additional things that need to be done:

- [ ] Rename file to `.mdx`
- [ ] Move the page under Database management section once it is done (https://github.com/memgraph/documentation/pull/765)
- [ ] Move the image to the new location under Database managment

**Review by kgolubic — COMMENTED** [review]
Everything looks OK.

**Pull request merged**
