### PR TITLE
BP - Deployment 

### PR DESCRIPTION
**Pull request by antejavor**
Best practices deployment PR: 

TODO (Ante) : 

- [x] Updated install current installs for Linux: https://github.com/memgraph/documentation/pull/661 @antejavor -> Stage 1
- [x] [Document Rockey/RedHat install process](https://github.com/memgraph/documentation/issues/669) https://github.com/memgraph/documentation/pull/672 @antejavor -> Stage 1
- [x] [Document CentOS install process](https://github.com/memgraph/documentation/issues/667) https://github.com/memgraph/documentation/pull/672 @antejavor -> Stage 1
- [x] [Document Fedora install process](https://github.com/memgraph/documentation/issues/668) https://github.com/memgraph/documentation/pull/672 @antejavor -> Stage 1
- [x] [Config page refactor](https://github.com/memgraph/documentation/pull/691) @antejavor -> Stage 1
- [ ] [Rhel 8 ](https://github.com/memgraph/documentation/issues/720) @antejavor -> Stage 2 (?)
- [x] Create Linux page under Deployment -> Stage 1
- [ ] Create Kubernetes page under Deployment -> Stage 2 -> May 22 due date
- [ ] Replication feedback: https://github.com/memgraph/memgraph/issues/1980 -> **Stage 2**
- [ ] Hardware and Memory tips guide -> **Stage 2**
- [ ] HA cluster setup linux page -> Stage 2
- [ ] Monitoring setup linux page -> Stage 2 

TODO (Matea): 
- [x] [Document the configuration of the docker-compose file better](https://github.com/memgraph/documentation/issues/670) @matea16  -> Stage 1
- [x] [Update configuration settings page](https://github.com/memgraph/documentation/issues/671) @matea16 -> Stage 1

TODO (Katarina)
- [x] https://github.com/memgraph/documentation/issues/696 @katarinasupe -> Stage 1
- [x] Create Docker page under Database management -> Stage 1
- [ ] Create Docker Compose page under Database management -> Stage 2 (?) TBD
- [ ] Create Cloud deployment page under Database management -> **Stage 2**
- [x] Add structural changes to the docs -> Stage 1
- [ ] HA cluster setup - Docker page -> Stage 2
- [ ] Monitoring - Docker page -> Stage 2

**Review all changed/transferred pages -> Stage 1**
- [x] Review Data durability under Fundamentals
- [x] Review Audit log under Logs
- [x] Review Authorization and Authentication
- [x] Review Database management
- [x] Review Backup and restore
- [x] Review Clustering
- [x] Review Query metadata
- [x] Review Monitoring
- [x] Review Text search under Querying

To be discussed on a daily: 
- [ ] https://github.com/memgraph/documentation/issues/695 -> **Stage 2**

Plan:

Wrap up Stage 1 by May 10, open new PR after that for Stage 2.

### Changes to structure

**New sections:**
Deployment (Docker, Docker Compose and Kubernetes)
Clustering

**Configuration restructure:**

- Configuration renamed to Database management
- Audit log has been deleted and transferred under Logs 
- Auth module has been deleted and placed under new Auth system integrations under Authentication and authorization
- Configuration settings renamed to Configuration
- Data durability and backup renamed to Backup and restore and Data durability knowledge transferred under Fundamentals
- High availability is transferred to Clustering
- Metadata renamed to Query metadata
- Monitoring server renamed to Monitoring
- Replication is placed under Clustering
- Security page is deleted and replaced by Authentication and authorization
- New page -> Authentication and authorization -> Users (old create user from Security), Role-based access control (old Role-based and Label-based from Security) and Auth system integrations (LDAP, OAuth, Auth module) under it 
- Text search has been transferred to Querying

Based on the structural changes above, redirects have to be added in, pages and links have to be reviewed.

**UPDATE**: Pages are reviews, links on those pages updated. **Links leading to old pages can be updated (are not yet) and redirects have to be added.**

NOTE: I still vote for Clustering under Database management (Kate)
NOTE: Whenever the format of /var/lib/memgraph changes, this is a breaking change if it's not made backwards compatible

### CODE REVIEW

**Comment by katarinasupe** [comment]
@antejavor should `MEMGRAPH_CONFIG` be listed in the Env vars table as well?

**Comment by katarinasupe** [comment]
@kgolubic This is basically done, but we need to resolve conflicts and see what the best time and way to merge, depending on the releases. Let's sync next week.

**Review by katarinasupe — APPROVED** [review]

**Comment by katarinasupe** [comment]
@kgolubic this is ready for review. Ante told me you can deal with conflicts. Let me know if something is unclear or needed from our side.

**Review by kgolubic — APPROVED** [review]
Everything looks OK.

**Pull request merged**
