### PR TITLE
Unique constraints as indices

### PR DESCRIPTION
**Pull request by Josipmrden**
### Description

Add docs to unique constraints as indices feature

### Pull request type

Please check what kind of PR this is:

- [X] Fix or improvement of an existing page
- [] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
[(especially necessary if the PR is related to a release)
](https://github.com/memgraph/memgraph/pull/1356)

### Checklist:

- [X] Check all content with Grammarly
- [X] Perform a self-review of my code
- [X] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [X] The build passes locally
- [X] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

### CODE REVIEW

**Comment by vpavicic** [comment]
@Josipmrden - if this is connected to the release, can you please merge it into the memgraph-2-12 branch?

**Comment by vpavicic** [comment]
The contents of this PR are no longer for memgraph 2-12... will need to create a PR pulling to memgraph-2-13

**Comment by kgolubic** [comment]
@Josipmrden is this PR ready for review?

**Comment by Josipmrden** [comment]
Closing for being stale

**Pull request closed without merging**
