### PR TITLE
Add 'GRANT DATABASE' to rbac

### PR DESCRIPTION
**Pull request by hal-eisen-MG**
### Description

Updated the role-based-access-control.mdx based on a [thread](https://discord.com/channels/842007348272169002/1278498722270937158) in Discord. Added a link in the main table for the DATABASE privilege which points to the new multi-tenancy page. Added "GRANT DATABASE" to several of the examples.

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)

Closes:
(paste the link to the issue it closes)

### Checklist:

- [ ] Check all content with Grammarly
- [x] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [x] The build passes locally
- [x] My changes generate no new warnings or errors
- [x] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

### CODE REVIEW

**Comment by antejavor** [comment]
But this is also an issue that inspired me to open this issue: 
https://memgraph.com/docs/database-management/authentication-and-authorization/role-based-access-control#manage-all-privileges-at-once 

After this command: 
```
GRANT ALL PRIVILEGES TO user;
```

User should have all permission, you still need to run these (next to the command above) : 

```
GRANT CREATE_DELETE ON LABELS * TO user;
GRANT CREATE_DELETE ON EDGE_TYPES * TO user;
```

**Review by antejavor — CHANGES_REQUESTED** [review]
But this is also an issue that inspired me to open this issue: 
https://memgraph.com/docs/database-management/authentication-and-authorization/role-based-access-control#manage-all-privileges-at-once 

After this command: 
```
GRANT ALL PRIVILEGES TO user;
```

User should have all permission, you still need to run these (next to the command above) : 

```
GRANT CREATE_DELETE ON LABELS * TO user;
GRANT CREATE_DELETE ON EDGE_TYPES * TO user;
```

To be able to create a node or relationship, while the docs suggest otherwise.

**Comment by katarinasupe** [comment]
@antejavor can you review/update this PR by the end of next week? (Nov 22)

**Review by antejavor — APPROVED** [review]
We have some non-logical steps there that are currently documented here: 

https://github.com/memgraph/documentation/pull/988/files

No matter the role grants, you still need to set the label-based, which is confusing, but this is problem on the product side: https://memgraph.slack.com/archives/C01BRQLQVAA/p1725631222620389?thread_ts=1725629345.933419&cid=C01BRQLQVAA

**Review by katarinasupe — APPROVED** [review]

**Pull request merged**
