### PR TITLE
Fetch edge by edge id

### PR DESCRIPTION
**Pull request by gvolfing**
### Description

Add description of new flag implemented in https://github.com/memgraph/memgraph/pull/1808/

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues
https://github.com/memgraph/memgraph/issues/1772

PR this doc page is related to: 
https://github.com/memgraph/memgraph/pull/1808/

Closes:
https://github.com/memgraph/memgraph/issues/1772

### Checklist:

- [x] Check all content with Grammarly
- [x] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [x] The build passes locally
- [x] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [x] If release-related, add release note on product PR

### CODE REVIEW

**Comment by katarinasupe** [comment]
Hi @gvolfing, can you give me an example of a query that would be faster with `--storage-enable-edges-metadata` set to `true`? I want to get a sense of how this feature works. My understanding is that specific queries would be faster, but this comes with memory costs for storing metadata.

**Comment by katarinasupe** [comment]
Found it here: https://github.com/memgraph/documentation/pull/502
So, any query that matches on edge type should be faster with the new flag enabled?

**Comment by gvolfing** [comment]
@katarinasupe 
https://github.com/memgraph/documentation/pull/502 is a different feature. https://github.com/memgraph/documentation/pull/502 is the feature, where we enable users to use edge-type indices in the first place. The issue is that usually when you have a graph problem you start from nodes and traverse the graph. However, in certain use-cases the user might want to start from edges. This is where https://github.com/memgraph/documentation/pull/502 helps because you can just get hold of every edge based on the given edge-type. An example query for that is `MATCH ()-[r:SOMEEDGETYPE]->() RETURN r`. As you can tell this is working just fine with Memgraph without https://github.com/memgraph/documentation/pull/502 however without edge-type indices this the worst possible scan in terms of performance, since we have to traverse the entire graph and check against every single relationship present. With https://github.com/memgraph/documentation/pull/502 it is possible to create an index based on the edge-type by using `CREATE EDGE INDEX ON :SOMEEDGETYPE` which will create and populate the index. Then consequent calls to `MATCH ()-[r:SOMEEDGETYPE]->() RETURN r` will just have to look up the index instead of traversing the entire graph.
This is https://github.com/memgraph/documentation/pull/502.

This feature on the other hand is an optimization for the case, where we want to look-up one single edge, based on it's ID. For example by using `MATCH ()-[r]->() WHERE r.id = 2 RETURN r`. Without this feature, this query translates to a SCANALL + EXPAND + FILTER operations on the logical plan level. The flag that is introduced here, `--storage-enable-edges-metadata` is enabling the use of additional memory to add metadata to edges. this will increase the memory usage, however it will allow us to do a logarithmic time lookup instead of the previuously mentioned set of operations.

So essentially, by enabling `--storage-enable-edges-metadata` is making queries like `MATCH ()-[r]->() WHERE r.id = 2 RETURN r` run potentially a lot faster, in exchange of memory.

**Review by kgolubic — APPROVED** [review]
Everything looks OK.

**Pull request merged**
