### PR TITLE
Typos: fixed an unclosed parentheses and another minor enhancement

### PR DESCRIPTION
**Pull request by YashasviMantha**
### Description

The CMakeLists.txt had an unclosed parentheses which resulted an error on execution. Closed it. Also corrected a minor grammar error. 

### Pull request type

Please check what kind of PR this is:

- [x] Fix or improvement of an existing page
- [ ] New documentation page, release related

### Related PRs and issues

PR this doc page is related to: 
(especially necessary if the PR is related to a release)

Closes:
Have not opened an issue for this. 

### Checklist:

- [x] Check all content with Grammarly
- [x] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [ ] The build passes locally
- [x] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

### CODE REVIEW

**Comment by YashasviMantha** [comment]
Not sure why my already merged commit is showing up on this one. Please do tell me if I did something wrong. :D

**Comment by kgolubic** [comment]
@YashasviMantha I'm not sure, but it maybe you didn't update your branch after we have merged your changes into our main branch.

**Review by kgolubic — APPROVED** [review]
Everything looks OK.

**Comment by kgolubic** [comment]
@YashasviMantha, thank you for these fixes!

**Pull request merged**
