### PR TITLE
[memgraph-2-12 < E-graphQL] Update docs after refactor for GraphQL and fix some mistakes

### PR DESCRIPTION
**Pull request by imilinovic**
### Description

Update docs after renaming procedure inputs and outputs to fit GraphQL mappings.

### Pull request type

Please check what kind of PR this is:

- [X] Fix or improvement of an existing page

### Related PRs and issues

PR this doc page is related to: 
[PR358](https://github.com/memgraph/mage/pull/358)

(especially necessary if the PR is related to a release)

Closes:
(paste the link to the issue it closes)

### Checklist:

- [x] Check all content with Grammarly
- [x] Perform a self-review of my code
- [ ] Make corresponding changes to the rest of the documentation (consult with the DX team)
- [x] The build passes locally
- [x] My changes generate no new warnings or errors
- [ ] Add a corresponding label
- [ ] If release-related, add a product and version label
- [ ] If release-related, add release note on product PR

### CODE REVIEW

**Review by imilinovic — COMMENTED** [review]
Looks good!

**Comment by imilinovic** [comment]
This is supposed to go in the next MAGE patch release -> so NOT memgraph 2.12 @vpavicic

**Comment by vpavicic** [comment]
> This is supposed to go in the next MAGE patch release -> so NOT memgraph 2.12 @vpavicic, so I guess we need a new branch for that.

Create a PR merging merge into main then!

**Comment by vpavicic** [comment]
new PR created 
https://github.com/memgraph/documentation/pull/201

**Pull request closed without merging**
